---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-repository-k8s
  labels:
    app: private-repository-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-repository-k8s
  template:
    metadata:
      labels:
        app: private-repository-k8s
    spec:
      volumes:
      - name: cert-vol
        secret:
          secretName: cert-secret
#        hostPath:
#         path: "/srv/registry/cert"
#         type: Directory
      - name: auth-vol
        secret:
          secretName: auth-secret
#       hostPath: 
#         path: "/srv/registry/auth"
#         type: Directory
      - name: repo-vol
        hostPath:
          path: "/srv/registry"
          type: Directory

      containers:
        - image: registry:2.7.0
          name: private-repository-k8s
          imagePullPolicy: IfNotPresent
          env:
          - name: REGISTRY_AUTH
            value: "htpasswd"
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: "/auth/htpasswd"
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/cert/tls.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/cert/tls.key"
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: cert-vol
            mountPath: "/cert"
            readOnly: true
          - name: auth-vol
            mountPath: "/auth"
            readOnly: true
          - name: repo-vol
            mountPath: "/registry"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    app: private-repository-k8s
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31320
  clusterIP: 10.106.32.26
