---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kf-dev
  name: test-train-1
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: val-acc 
    #objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      #- Train-accuracy
      - train-loss
  algorithm:
    algorithmName: random
  parallelTrialCount: 5
  maxTrialCount: 6
  maxFailedTrialCount: 2
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
    - name: batch-size
      parameterType: int
      feasibleSpace:
        min: "16"
        step: "16"
        max: "128"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
          - adagrad
          - adadelta
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: batchSize
        description: Batch size of training data
        reference: batch-size
    #  - name: numberLayers
    #    description: Number of training model layers
    #    reference: num-layers
      - name: optimizer
        description: Training model optimizer (sdg, adam or ftrl)
        reference: optimizer
    retain: true # test for metics overview per tria:q
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        ttlSecondsAfterFinished: 5
        template:
          metadata:
            annotations: 
              sidecar.istio.io/inject: "false"
          spec:
            volumes:
              - name: data-vol
                nfs:
                  server: "${NFS_CLUSTER_IP}"
                  path: /data
                  #readOnly: false
              - name: varlog
                emptyDir:
                  sizeLimit: 500Mi
            imagePullSecrets:
              - name: image-registry-secret
            restartPolicy: Never
            containers:
              - name: training-container
                image: image-registry:5000/rs-models
                command:
                  #- "python3"
                  #- "/opt/mxnet-mnist/mnist.py"
                  #- "--batch-size=64"
                  #- "--lr=${trialParameters.learningRate}"
                  #- "--num-layers=${trialParameters.numberLayers}"
                  #- "--optimizer=${trialParameters.optimizer}"
                  #- "--gpus=0"
                  #--------------------
                  - "./app/models"
                  - "vit"
                  - "--load-data data/processed/SMA_10"
                  - "--lr=${trialParameters.learningRate}"
                  - "--batch-size=${trialParameters.batchSize}"
                  - "--optim=${trialParameters.optimizer}"
                  - "--epochs=5"
                resources:
                  limits:
                    memory: "3Gi"
                    cpu: "2"
                    nvidia.com/gpu: 1
                volumeMounts:
                  - name: data-vol
                    mountPath: /data
                  - name: varlog
                    mountPath: /var/log
