---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kf-dev
  name: random-homemade-image
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
#    - name: num-layers
#      parameterType: int
#      feasibleSpace:
#        min: "2"
#        max: "5"
#    - name: optimizer
#      parameterType: categorical
#      feasibleSpace:
#        list:
#          - sgd
#          - adam
#          - ftrl
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: learning_rate
      #- name: numberLayers
      #  description: Number of training model layers
      #  reference: num-layers
      #- name: optimizer
      #  description: Training model optimizer (sdg, adam or ftrl)
      #  reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations: 
              sidecar.istio.io/inject: "false"
          spec:
            imagePullSecrets:
              - name: image-registry-secret
            containers:
              - name: training-container
                image: image-registry:5000/rs-mdl
                #ports:
                #  - containerPort: 5000
                #image: docker.io/kubeflowkatib/mxnet-mnist:latest
                command:
                  #- "python3"
                  #- "/opt/mxnet-mnist/mnist.py"
                  #- "--batch-size=64"
                  - "linear"
                  - "--learning_rate=${trialParameters.learningRate}"
                  #- "--num-layers=${trialParameters.numberLayers}"
                  #- "--optimizer=${trialParameters.optimizer}"
                  #- "--gpus=0"
                resources:
                  limits:
                    memory: "1Gi"
                    cpu: "1"
                    #nvidia.com/gpu: 1
            restartPolicy: Never
