apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
  - name: data-vol
    nfs:
      #server: nfs-service.storage.svc.cluster.local # Hard code ip due to bug in DNS
      server: "${NFS_CLUSTER_IP}"
      path: /data
      readOnly: false
  containers:
    - name: transmute-into-images
      image: image-registry:5000/rs-transmute
      ports:
        - containerPort: 5000
      volumeMounts:
      - name: data-vol
        mountPath: /data
      command: [ "sleep" ]
      args: [ "infinity" ]
      resources:
        limits:
          cpu: "2"
        requests:
          cpu: "1"
  imagePullSecrets:
    - name: image-registry-secret
  restartPolicy: Never
