# This is needed if dynamic provision is used
#---
## Declare the volume claim
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: grafana-pvc
#  namespace: monitoring
#  labels:
#    app: grafana
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: nfs-storage
#  resources:
#    requests:
#      storage: 5Gi
