---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  namespace: storage
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      nodeName: "${CTLPLN_NODE}"
      containers:
      - name: nfs-server
        image: registry.k8s.io/volume-nfs:0.8
        ports:
        - name: nfs
          containerPort: 2049
          protocol: TCP
        - name: mountd
          containerPort: 6666
          protocol: TCP
        - name: rpcbind
          containerPort: 111
          protocol: UDP
        securityContext:
          privileged: true
        volumeMounts:
        - name: storage
          mountPath: /exports
      volumes:
      - name: storage
        hostPath:
          path: ${NFS_PATH} # store all data in "/path/to/nfs" directory of the node where it is running
          type: DirectoryOrCreate # if the directory does not exist then create it
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: storage
spec:
  clusterIP: ${NFS_CLUSTER_IP} # Hard coded due to DNS-bug in kubernetes
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 6666
  - name: rpcbind
    port: 111
    protocol: UDP
  selector:
    app: nfs-server # must match with the label of NFS pod
