# Create persistent volumnes for Kubeflow
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-katib-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default-storage
  local:
    path: "${KF_KATIB_PV_PATH}"
  claimRef: 
    name: katib-mysql
    namespace: kubeflow
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - ${WORKER_NODE_1}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-authservice-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default-storage
  local:
    path: "${KF_AUTH_PV_PATH}"
  claimRef: 
    name: authservice-pvc
    namespace: istio-system
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${WORKER_NODE_1}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-mysql-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default-storage
  local:
    path: "${KF_MYSQL_PV_PATH}"
  claimRef:
    name: mysql-pv-claim
    namespace: kubeflow
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${WORKER_NODE_1}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-minio-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default-storage
  local:
    path: "${KF_MINIO_PV_PATH}"
  claimRef:
    name: minio-pvc
    namespace: kubeflow
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${WORKER_NODE_1}
