---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-registry
  namespace: registry
  labels:
    app: image-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-registry
  template:
    metadata:
      labels:
        app: image-registry
    spec:
      tolerations:
      - key: special
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: cert-vol
        secret:
          secretName: cert-secret
      - name: auth-vol
        secret:
          secretName: auth-secret
      - name: repo-vol
        nfs:
          #server: nfs-service.storage.svc.cluster.local # Hard code ip due to bug in DNS
          server: "${NFS_CLUSTER_IP}"
          path: "/registry"
          readOnly: false
      containers:
        - image: registry:2.8.3
          name: image-registry
          imagePullPolicy: IfNotPresent
          env:
          - name: REGISTRY_AUTH
            value: "htpasswd"
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
            value: "Registry"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: "/auth/htpasswd"
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/cert/tls.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/cert/tls.key"
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: cert-vol
            mountPath: "/cert"
            readOnly: true
          - name: auth-vol
            mountPath: "/auth"
            readOnly: true
          - name: repo-vol
            mountPath: "/var/lib/registry"
