# Create service for the registry
---
apiVersion: v1
kind: Service
metadata:
  name: image-registry
  namespace: registry
spec:
  selector:
    app: image-registry
#  nodeSelector:
#    special: control-plane
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: ${DOCKER_NODEPORT}
  clusterIP: "${DOCKER_CLUSTER_IP}"
