---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-registry
  namespace: registry
  labels:
    app: image-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-registry
  template:
    metadata:
      labels:
        app: image-registry
    spec:
      nodeSelector:
        nodetype: storage
      volumes:
      - name: cert-vol
        secret:
          secretName: cert-secret
      - name: auth-vol
        secret:
          secretName: auth-secret
      - name: repo-vol
        persistentVolumeClaim:
          claimName: docker-repo-pvc
      containers:
        - image: registry:2.7.0
          name: image-registry
          imagePullPolicy: IfNotPresent
          env:
          - name: REGISTRY_AUTH
            value: "htpasswd"
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: "/auth/htpasswd"
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/cert/tls.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/cert/tls.key"
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: cert-vol
            mountPath: "/cert"
            readOnly: true
          - name: auth-vol
            mountPath: "/auth"
            readOnly: true
          - name: repo-vol
            mountPath: "/var/lib/registry"
