# This this will be needed if dynamic provision is used.
#---
## Declare the volume claim
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: docker-repo-pvc
#  namespace: registry
#  labels:
#    app: image-registry
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: nfs-storage
#  resources:
#    requests:
#      storage: 5Gi
